name: Fetch Docker Tags Count

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Docker image name'
        required: true
        default: 'nginx'

jobs:
  fetch-tags:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up jq
        run: sudo apt-get install -y jq

      - name: Fetch Docker tags count
        run: |
          IMAGE_NAME="${{ github.event.inputs.image }}"
          echo "Fetching tags for Docker image: $IMAGE_NAME"
          
          TAGS_JSON=$(curl -s "https://registry.hub.docker.com/v2/repositories/library/$IMAGE_NAME/tags")
          TAG_COUNT=$(echo $TAGS_JSON | jq '.results | length')
          
          echo "Number of tags available for $IMAGE_NAME: $TAG_COUNT"
