name: Manage Docker Tags

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight

jobs:
  manage-docker-tags:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install jq (JSON Processor) and authenticate Docker Hub
      - name: Install jq and Authenticate Docker Hub
        run: |
          sudo apt-get install -y jq
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Step 2: Count Tags in Docker Hub
      - name: Fetch Docker Image Tags
        id: fetch_tags
        run: |
          IMAGE="username/repository" # Replace with your Docker Hub image
          TAGS_URL="https://hub.docker.com/v2/repositories/${IMAGE}/tags/"

          echo "Fetching tags for $IMAGE..."

          # Paginate and collect all tags
          TAGS=()
          NEXT_PAGE=$TAGS_URL

          while [ "$NEXT_PAGE" != "null" ]; do
            RESPONSE=$(curl -s $NEXT_PAGE)
            TAGS+=( $(echo $RESPONSE | jq -r '.results[].name') )
            NEXT_PAGE=$(echo $RESPONSE | jq -r '.next')
          done

          echo "Found ${#TAGS[@]} tags"
          echo "tags=${TAGS[*]}" >> $GITHUB_ENV
          echo "tag_count=${#TAGS[@]}" >> $GITHUB_ENV

      # Step 3: Delete Old Tags if Count Exceeds 10
      - name: Delete Old Tags
        if: env.tag_count > 10
        run: |
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/python-app"
          TAGS=(${{ env.tags }})
          KEEP=10 # Number of tags to keep (most recent)

          echo "Deleting older tags..."

          # Loop through all tags except the latest 'KEEP'
          for ((i=0; i<${#TAGS[@]} - KEEP; i++)); do
            TAG=${TAGS[$i]}
            echo "Deleting tag: $TAG"
            curl -X DELETE -u "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_PASSWORD }}" \
            "https://hub.docker.com/v2/repositories/${IMAGE}/tags/${TAG}/"
          done

          echo "Old tags deleted successfully."
