name: Delete Old Docker Tags

on:
  workflow_dispatch:

jobs:
  delete-tags:
    runs-on: ubuntu-22.04  # You can change the version as per your requirement

    steps:
    # Step 1: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 2: Fetch Docker Image Tags from the repository
    - name: Fetch Docker Image Tags
      id: fetch_tags
      run: |
        TAGS_URL="https://hub.docker.com/v2/repositories/sivathavva/python/tags/"
        echo "Fetching tags for sivathavva/python ...."

        # Initialize variables
        TAGS=()
        NEXT_PAGE=$TAGS_URL
        UNIQUE_TAGS=()

        # Fetch tags from all pages
        while [ "$NEXT_PAGE" != "null" ]; do
          RESPONSE=$(curl -s $NEXT_PAGE)

          # Extract tags from the response and avoid duplicates
          for TAG in $(echo "$RESPONSE" | grep -o '"name":"[^"]*' | sed 's/"name":"//'); do
            if [[ ! " ${UNIQUE_TAGS[@]} " =~ " ${TAG} " ]]; then
              UNIQUE_TAGS+=("$TAG")
            fi
          done

          # Get the next page URL
          NEXT_PAGE=$(echo "$RESPONSE" | grep -o '"next":"[^"]*' | sed 's/"next":"//' | sed 's/\\"//g')
          NEXT_PAGE=${NEXT_PAGE:-null}  # Handle null next page
        done

        # Output the tags and tag count
        echo "Found ${#UNIQUE_TAGS[@]} unique tags"
        echo "tags=${UNIQUE_TAGS[*]}" >> $GITHUB_ENV
        echo "tag_count=${#UNIQUE_TAGS[@]}" >> $GITHUB_ENV

    # Step 3: Delete Old Tags if Age Exceeds 10 Days
    - name: Delete Old Tags if Age Exceeds 10 Days
      run: |
        IMAGE="sivathavva/python-app"
        TAGS=(${{ env.tags }})
        KEEP_DAYS=5
        CURRENT_DATE=$(date +%Y%m%d%H%M%S)  # Get current date in YYYYMMDDHHMMSS format
        CURRENT_TIMESTAMP=$(date -d "$CURRENT_DATE" +%s)  # Convert current date to Unix timestamp
        echo "Deleting tags older than $KEEP_DAYS days..."

        for TAG in "${TAGS[@]}"; do
          # Check if tag follows the timestamp format YYYYMMDDHHMMSS
          if [[ "$TAG" =~ ^[0-9]{14}$ ]]; then
            TAG_TIMESTAMP=$TAG
            TAG_DATE=$(date -d "$TAG_TIMESTAMP" +%s)  # Convert tag timestamp to Unix timestamp

            # Calculate the age of the tag in days
            AGE=$(( (CURRENT_TIMESTAMP - TAG_DATE) / 86400 ))  # 86400 seconds in a day

            # If the tag is older than 10 days, delete it
            if [ $AGE -gt $KEEP_DAYS ]; then
              echo "Deleting tag: $TAG (Age: $AGE days)"
              curl -X DELETE -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" \
              "https://hub.docker.com/v2/repositories/sivathavva/python/tags/${TAG}/"
            else
              echo "Skipping tag: $TAG (Age: $AGE days)"
            fi
          else
            echo "Skipping invalid tag: $TAG (Invalid format)"
          fi
        done

        echo "Old tags deletion completed."
