name: Count Docker Images

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  count-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login my.registry.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Fetch and Count Images
        run: |
          echo "Fetching images from registry..."
          TOKEN=$(curl -s -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" \
            "https://my.registry.com/v2/_catalog" | jq -r '.repositories | length')
          
          echo "Total number of images in the private registry: $TOKEN"
          echo "IMAGE_COUNT=$TOKEN" >> $GITHUB_ENV

      - name: Display Image Count
        run: |
          echo "Total Docker Images: $IMAGE_COUNT"
