name: Delete Old Docker Tags if Count > 10

on:
  workflow_dispatch: # Trigger manually

jobs:
  delete_old_tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get All Tags
        id: tags
        run: |
          # Fetch the tags for the repository from Docker Hub
          TAGS=$(curl -s https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}/tags/list)
          # Parse the tag list
          echo "::set-output name=tags::$TAGS"

      - name: Check Tag Count and Delete Old Tags If More Than 10
        run: |
          TAGS=${{ steps.tags.outputs.tags }}
          TAG_LIST=$(echo $TAGS | jq -r '.tags[]')
          TAG_COUNT=$(echo "$TAG_LIST" | wc -w)
          echo "Number of tags: $TAG_COUNT"
          
          if [ "$TAG_COUNT" -gt 10 ]; then
            echo "Tag count exceeds 10, proceeding to delete old tags..."
            
            # Sort tags by creation date (this assumes tags are ordered by creation date in the registry)
            TAG_LIST_OLD=$(echo $TAGS | jq -r '.tags | sort_by(.created) | .[:10]')
            
            # Loop through and delete the oldest tags
            for TAG in $TAG_LIST_OLD; do
              echo "Getting digest for $TAG"
              # Get the digest of the tag
              DIGEST=$(curl -s --header "Accept: application/vnd.docker.distribution.manifest.v2+json" \
                  https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}/manifests/$TAG | jq -r '.config.digest')
              
              if [ "$DIGEST" != "null" ]; then
                echo "Deleting tag $TAG with digest $DIGEST"
                # Send DELETE request to remove the tag
                curl -X DELETE https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}/manifests/$DIGEST
              else
                echo "Tag $TAG not found"
              fi
            done
          else
            echo "Tag count is less than or equal to 10, skipping deletion."
          fi
