name: Count Docker Images

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  count-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Fetch and Count Images with Pagination
        run: |
          echo "Fetching all images from the private registry..."
          REGISTRY_URL="https://my.registry.com/v2/_catalog?n=2"  # Adjust 'n' as per registry limits
          REPO_LIST=""
          NEXT_URL=$REGISTRY_URL
          
          while [ -n "$NEXT_URL" ]; do
            echo "Fetching from: $NEXT_URL"
            RESPONSE=$(curl -s -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" "$NEXT_URL")
            REPOS=$(echo "$RESPONSE" | jq -r '.repositories[]')
            REPO_LIST="$REPO_LIST $REPOS"
            
            # Check for pagination link
            LINK_HEADER=$(curl -I -s -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" "$NEXT_URL" | grep -i 'Link:')
            if [[ "$LINK_HEADER" =~ \<([^>]*)\>\;\ rel=\"next\" ]]; then
              NEXT_URL=${BASH_REMATCH[1]}
            else
              NEXT_URL=""
            fi
          done

          # Count total images
          IMAGE_COUNT=$(echo "$REPO_LIST" | wc -w)
          echo "Total number of images in the private registry: $IMAGE_COUNT"
          echo "IMAGE_COUNT=$IMAGE_COUNT" >> $GITHUB_ENV

      - name: Display Image Count
        run: |
          echo "Total Docker Images: $IMAGE_COUNT"
