name: Fetch Docker Image Tags Count

on:
  workflow_dispatch: # Allows manual trigger
  push:              # Trigger on push to the repo
    branches:
      - main

jobs:
  fetch-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Fetch Image Tags Count
        env:
          REPOSITORY: ${{ secrets.DOCKER_REPO }}  # Replace with your repository
          DOCKER_REGISTRY: "https://hub.docker.com/v2" # Modify for other registries
        run: |
          echo "Fetching tags for repository: $REPOSITORY"

          # Get tags list from Docker Registry API
          TAGS=$(curl -s -u "$DOCKER_USERNAME:$DOCKER_PASSWORD" \
            "$DOCKER_REGISTRY/repositories/${REPOSITORY}/tags" | jq '.results | length')

          echo "Total tags count: $TAGS"

      - name: Print Success
        run: echo "Docker image tags count fetched successfully!"
