name: Fetch Docker Image Count

on:
  workflow_dispatch:

jobs:
  fetch-image-count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fetch Tags from Docker Registry
        id: fetch_tags
        run: |
          REPO_USER="sivathavva"
          IMAGE_NAME="python-app"

          # Call Docker Hub API to fetch tags
          TAGS_JSON=$(curl -s "https://registry.hub.docker.com/v2/repositories/${REPO_USER}/${IMAGE_NAME}/tags/")
          
          # Parse the tags and count
          TAG_COUNT=$(echo "$TAGS_JSON" | jq '.results | length')

          # Print and export the tag count
          echo "Number of tags: $TAG_COUNT"
          echo "tag_count=$TAG_COUNT" >> $GITHUB_ENV

      - name: Output Image Count
        run: |
          echo "Docker Image Count: ${{ env.tag_count }}"
